### PR TITLE
Release r24.02.1

### PR DESCRIPTION
**Pull request by renato-arantes**
Pytorch updates:

- Update Pytorch® README.md
- Downgrade OpenBLAS to version 0.3.26

### CODE REVIEW

**Comment by snadampal** [comment]
Hi @renato-arantes , why is the OpenBLAS downgrade required? any known issues with the latest version?
looks like you downgraded it from `0.3.26` to `0.3.24`. We are using `0.3.25` for torch wheels for quite sometime and it's working fine.
```
  -  OPENBLAS_VERSION=0.3.26 \
  +  OPENBLAS_VERSION=0.3.24 \
```

**Comment by renato-arantes** [comment]
Hi @snadampal,

Yes! we were getting `Illegal instruction (core dumped)` with `0.3.26` and had to downgrade the OpenBLAS version. We downgraded to `0.3.24` because it is a version that adds major changes for ARM. We can try `0.3.25` on the next release.

**Comment by snadampal** [comment]
can you please share the reproducer for the core dump

> we were getting Illegal instruction (core dumped) with 0.3.26

is someone investigating this? or has it been raised in openblas repo?

**Comment by renato-arantes** [comment]
Hi @snadampal,

To reproduce it you can execute the bellow command on c6g AWS instance:

**Pull request merged**
